version: "3"

services:
  minio:
    image: docker.io/bitnami/minio:2024.10.13-debian-12-r0
    container_name: experiments_minio
    # restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      # - MINIO_ACCESS_KEY=12345678
      # - MINIO_SECRET_KEY=password
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=anigil123
      - CONSOLE_ACCESS_KEY=test
      - CONSOLE_SECRET_KEY=test
    # command: server --address ":9000" --console-address ":9001" /data
    volumes:
      - minio_data:/data

volumes:
  minio_data:
    external: true
