apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-test
  namespace: tools # dont use ns vault and kube-system, details kubectl describe MutatingWebhookConfiguration vault-secrets-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vault
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vault
      # annotations:
      #   vault.security.banzaicloud.io/vault-addr: "https://vault-cluster.local.geracorp.work" # optional, the address of the Vault service, default values is https://vault:8200
      #   vault.security.banzaicloud.io/vault-role: "default" # optional, the default value is the name of the ServiceAccount the Pod runs in, in case of Secrets and ConfigMaps it is "default"
      #   vault.security.banzaicloud.io/vault-skip-verify: "true" # optional, skip TLS verification of the Vault server certificate
      #   vault.security.banzaicloud.io/vault-path: "kubernetes" # optional, the Kubernetes Auth mount path in Vault the default value is "kubernetes"
    spec:
      serviceAccountName: default
      containers:
      - name: alpine
        image: alpine
        command: ["sh", "-c", "echo $FOO && echo going to sleep... && sleep 10000"]
        env:
        - name: FOO
          value: vault:secret/data/github2telegram-bot#BOT_TOKEN
