kind: ServiceAccount
apiVersion: v1
metadata:
  name: vault
  namespace: vault-infra
secrets:
  - name: vault-token
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: vault-infra
  annotations:
    kubernetes.io/service-account.name: vault
type: kubernetes.io/service-account-token

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault
  namespace: vault-infra
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "update", "patch"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault
  namespace: vault-infra
roleRef:
  kind: Role
  name: vault
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: vault-infra

---
# This binding allows the deployed Vault instance to authenticate clients
# through Kubernetes ServiceAccounts (if configured so).
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: vault-infra
