apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab-system
spec:
  chart:
    version: "${chartVersion}" # https://gitlab.com/gitlab-org/cloud-native/gitlab-operator/-/blob/<OPERATOR_VERSION>/CHART_VERSIONS
    values:
      global:
        hosts:
          domain: geracorp.ru # use a real domain here
        ingress:
          configureCertmanager: true
          class: traefik
        appConfig:
          pipeline:
            enableJobJwt: true # включение JWT токенов
      nginx-ingress:
        enabled: false
      certmanager-issuer:
        email: exandore@gmail.com # use your real email address here
      gitlab:
        webservice:
          replicaCount: 1 # установка начального количества реплик для gitlab-webservice
      webservice:
        hpa:
          enabled: true
          minReplicas: 1 # минимальное количество реплик
          maxReplicas: 5 # максимальное количество реплик
          metrics:
            - type: Resource
              resource:
                name: cpu
                target:
                  type: Utilization
                  averageUtilization: 80
